### ISSUE TITLE
Enable URL alias sidebar through settings.

### ISSUE THREAD

**Issue by boazpoolman** [strapi-community/strapi-plugin-url-alias#15]
### Summary

As of now each content type that is visible in the content editor view will get the URL alias fields attached to it by the plugin.
Though you might only need the URL alias functionality for one of your content types.
Having said that it makes sense to let the user enable the sidebar instead of having the plugin enable it for all content types without notice

### Suggested solution(s)

I want to have a checkbox in the CT settings just like how you can enable localizations for a CT. 
See the screenshot below

<img width="1512" alt="Schermafbeelding 2022-08-28 om 22 02 06" src="https://user-images.githubusercontent.com/9551934/187092343-b98777d1-d8f0-4b5b-9a7b-37968d424fc7.png">

**Comment by numr** [comment]
I also think this is a problem，i hope solve it
