### ISSUE TITLE
Be able to choose which content types that url alias applies to

### ISSUE THREAD

**Issue by Alexnortung** [strapi-community/strapi-plugin-url-alias#19]
### Summary

For some content types, it does not make sense to have a url. But for all content types there are shown a url alias field.

### Why is it needed?

It can be confusing for the end user why there is a url field for content types that does not have a url.

### Suggested solution(s)

* Make it possible to define which content types url alias applies to (or should be ignored) in the plugins config file

**Comment by boazpoolman** [comment]
Duplicate of #15

**Comment by Alexnortung** [comment]
Thanks!
