### ISSUE TITLE
findMany in content-api?

### ISSUE THREAD

**Issue by StevenGFX** [strapi-community/strapi-plugin-url-alias#2]
Can findMany be added to the content-api for the ability to get all pages with their aliases?

**Comment by boazpoolman** [comment]
Hey @StevenGFX

Thanks for your feature request.

Do you want to fetch all pages that have an URL alias, or do you want to fetch all URL aliases?
Also; could you elaborate on why you need this?

Looking forward to here from you 🙂

**Comment by StevenGFX** [comment]
I think I was a bit premature on this request, so I'll go ahead and close it out. This module does all that I need! Really appreciate your work here!
