### ISSUE TITLE
Error when trying to delete locale

### ISSUE THREAD

**Issue by Alexnortung** [strapi-community/strapi-plugin-url-alias#26]
### Describe the bug

When trying to delete a locale I am just met with a generic strapi error in the interface. In the console I am getting a more detailed error:

```
[2023-02-08 14:29:42.995] error: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at Object.beforeDeleteMany (/home/.../node_modules/@strapi-community/strapi-plugin-url-alias/server/admin-api/services/lifecycle.js:125:47)
```

### Steps to reproduce the behavior

1. Create a new locale by going to Settings -> Internationalization -> + Create new locale
2. click on the delete button next to it and confirm
3. You will be met with a similar error

### Expected behavior

The locale would be deleted

### System

- Node.js version: 
- NPM version: 9
- Strapi version: 4.6.0
- Plugin version: 1.0.0-alpha.6
- Database: sqlite
- Operating system: NixOS (Linux)

**Comment by boazpoolman** [comment]
Thank you for submitting this issue.
I will try and reproduce it as soon as I have the time.
