### ISSUE TITLE
Get path information on regular API responses

### ISSUE THREAD

**Issue by Norbz** [strapi-community/strapi-plugin-url-alias#48]
### Summary

Inject the path for which the data could be accesible when calling the default strapi API (find, or findOne)

### Why is it needed?

Sometimes, you still need to load some data the old fashioned way, for a search engine for instance. When getting the result, you may want to navigate your frontend toward their url-alias.

Right now, we only retrieve the url_path_id, but we have no findOne action on the path content-type.

### Suggested solution(s)

The technical solution may differ according to the potential data structure.
- Keeping the current datastructure but enforcing a relationship, this should work by default with populate options
- Keeping the current datastructure with no relationship or changing the datastructure, this should be populated by a middleware

### Suggested Workaround
If someone needs the feature until developed, as for the beta 9 version, I got it working by adding a global middleware like this :

```
'use strict';

/**
 * `inject-url-alias` middleware
 */

module.exports = (config, { strapi }) => {
  return async (ctx, next) => {
    await next();

    if (!ctx.body) {
      return;
    }

    const apiPrefix = strapi.config.api?.rest?.prefix || "/api/";
    if (ctx.request && ctx.request.url && ctx.request.url.indexOf(apiPrefix) !== -1) {
      const { data } = ctx.body;
      if (data && data.attributes && data.attributes.url_path_id) {
          const entry = await strapi.db.query("plugin::url-alias.path").findOne({
              select: ['id', 'url_path'],
              where: {id: data.attributes.url_path_id}
          });
          
          data.attributes.url_alias = entry;

          delete data.attributes.url_path_id;
      } else if(Array.isArray(data) && data.length > 0){
        const entries = await strapi.db.query("plugin::url-alias.path").findMany({
          select: ['id', 'url_path'],
        });

        data.map((model, index) => {
          const path = entries.find((p)=>p.id === parseInt(model.attributes.url_path_id))

          model.attributes.url_alias = path
          delete model.attributes.url_path_id;
        })
      }
    }
  };
};

```

⚠️ It only works for the data being called, and will not look for other data in relationships

**Comment by Alexnortung** [comment]
This has always been there and is in the latest version. You are right that it was not there in alpha.9, but that was due to a bug.

Try with the latest version, or else I am unsure what you are requesting :)

**Comment by Norbz** [comment]
Oh, didn't saw the beta 10. To be fair, it's less that one day old ^^
I was working on a project with another dev, and we needed the path. I worked on the solution for the project then wrote the bug.

Ill try the beta.10 and close if necessary

**Comment by boazpoolman** [comment]
@Alexnortung is right. The code for this is provided by the plugin.

The plugin actually overwrites the core `strapi.entityService` and other query APIs to have their `findOne` and `findMany` methods be altered to insert the `url_path` field in their responses.

It's definitely not a great solution. But it is effective.

**Comment by Alexnortung** [comment]
I think a better solution would just be to use lifecycle hooks. Another plugin that alters the API response is strapi plugin populate deep.

**Comment by boazpoolman** [comment]
Pretty cool how the populate deep plugin alters the response.

**Comment by boazpoolman** [comment]
Pretty cool how the populate deep plugin alters the response.
They just change the populate param before the query is done.
No need to rewrite the response.

This might be another incentive to go with an actual DB level relation, from url path to content type.
Then we can just auto populate them the way the populate deep plugin does.
