### ISSUE TITLE
Ability to use populate with the REST API

### ISSUE THREAD

**Issue by tcherokee** [strapi-community/strapi-plugin-url-alias#5]
## Feature request
I would like the ability to use `populate` with the rest API

### Summary

At the moment, relations, media fields and components which need the `populate` parameter to show are not available via the REST API. This restricts the scenarios in which the plugin can be used. The ability to use the `populate` parameter will ensure that the using the URL Alias Endpoint will allow you to get all the content associated with that page/collection.

**Comment by boazpoolman** [comment]
This was fixed in alpha.4
